# Generated by Django 4.0.5 on 2022-06-26 03:25

from django.db import migrations, models
import youtubeapp.backend


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=youtubeapp.backend.MediaStorage),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_thumbnail',
            field=models.ImageField(upload_to=youtubeapp.backend.MediaStorage),
        ),
    ]
