# Generated by Django 4.0.5 on 2022-06-26 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0002_alter_video_video_alter_video_video_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_thumbnail',
            new_name='video1thumbnail',
        ),
    ]
